os: osx
language: objective-c
osx_image: xcode11

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

jobs:
  include:
    - stage: iOS test
      script:
        - set -o pipefail
        - xcodebuild -project PiDash-iOS/PiDash.xcodeproj -scheme PiDash -destination platform\=iOS\ Simulator,OS\=13.0,name\=iPhone\ Xs build test | xcpretty
    - stage: deploy
      script: tar -cvzf server.tar.gz PiDash-Server
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "server.tar.gz"
        skip_cleanup: true
